version: "3"
services:

  db:
    environment:
      - ORACLE_PWD=<password>
    image: container-registry.oracle.com/database/express:latest
    container_name: xe21c
    ports:
      - 1521:1521
    hostname: xedatabase
    networks:
      - ords-database-network
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'select 1 from dual;' | ORACLE_HOME=/opt/oracle/product/21c/dbhomeXE /opt/oracle/product/21c/dbhomeXE/bin/sqlplus -s USERNAME/PASSWORD@localhost"]
      interval: 30s
      retries: 60
      timeout: 60s

  ords:
    image: container-registry.oracle.com/database/ords:latest
    depends_on:
      db:
        condition: service_healthy
    container_name: ords
    ports:
      - 8181:8181
    networks:
      - ords-database-network
    volumes:
      - <Update to your directory holding ORDS secret>:/opt/oracle/variables

networks:
  ords-database-network:
    driver: bridge
